# Generated by Django 2.2.6 on 2019-11-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='Ali', upload_to='pics/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=('Ali', 'Aliasghar'), max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
