# Generated by Django 2.2.6 on 2019-11-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_auto_20191119_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics/'),
        ),
    ]
