# Generated by Django 2.2.7 on 2020-01-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_auto_20191213_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='RF_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='balance',
        ),
        migrations.AlterField(
            model_name='customer',
            name='roll_no',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
