# Generated by Django 2.2.6 on 2019-11-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_auto_20191122_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='image', upload_to='pics/'),
            preserve_default=False,
        ),
    ]
