# Generated by Django 2.2.7 on 2019-12-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='RF_id',
        ),
    ]
