# Generated by Django 2.2.7 on 2020-02-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancecheck',
            name='earnings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
