# Generated by Django 2.2.7 on 2020-02-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200207_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancecheck',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
