# Generated by Django 2.2.7 on 2019-12-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191213_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='RF_id',
            new_name='customer',
        ),
    ]
