# Generated by Django 2.2.7 on 2020-02-06 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_custom_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_item',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_items', to='orders.Order'),
        ),
    ]
