# Generated by Django 2.2.7 on 2020-02-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_custom_item_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoSystem',
            fields=[
                ('pos_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('petty_cash', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
