# Generated by Django 2.2.7 on 2020-02-07 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_posystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posystem',
            name='petty_cash',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BalanceCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_b', models.FloatField(blank=True, null=True)),
                ('ending_b', models.FloatField(blank=True, null=True)),
                ('petty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.PoSystem')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
